#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Nuclear
  module Vote
    YES = 1
    NO = 2
    VALUE_MAP = {1 => "YES", 2 => "NO"}
    VALID_VALUES = Set.new([YES, NO]).freeze
  end

  module Status
    ABORTED = 1
    COMMITED = 2
    PENDING = 3
    VALUE_MAP = {1 => "ABORTED", 2 => "COMMITED", 3 => "PENDING"}
    VALID_VALUES = Set.new([ABORTED, COMMITED, PENDING]).freeze
  end

end
